name: Ejecutar Terraform

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: 'Contexto desde Port'
        required: false
        default: '{}'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Mostrar el contexto de Port
      run: |
        echo "Recibiendo el contexto desde Port: ${{ github.event.inputs.port_context }}"
        echo "Bucket Name: ${{ github.event.inputs.bucket_name }}"
    
    - name: Ejecutar Terraform
      run: |
        cd modules/bucket/
        terraform init
        terraform apply -auto-approve -var="bucket_name=ami-abc123"
