name: Ejecutar Terraform

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: 'Contexto desde Port'
        required: false
        default: '{}'
      bucket_name:
        description: 'Nombre del bucket'
        required: true
      environment:
        description: 'Nombre del bucket'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Ejecutar Terraform
      run: |
        aws sts get-caller-identity
        cd modules/bucket/
        terraform init
        terraform apply -auto-approve -var="bucket_name=${{ github.event.inputs.bucket_name }}" -var="environment=${{ github.event.inputs.environment }}"

    - name: Report to Port
      run: |
        curl -X POST https://api.getport.io/v1/buckets \
          -H "Authorization: Bearer ${{ secrets.PORT_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "${{ github.event.inputs.bucket_name }}",
            "type": "aws_s3_bucket",
            "properties": {
              "region": "us-east-1"
            }
          }'