name: Ejecutar Terraform

on:
  workflow_dispatch:
    inputs:
      port_context:
        description: 'Contexto desde Port'
        required: false
        default: '{}'
      bucket_name:
        description: 'Nombre del bucket'
        required: true
      environment:
        description: 'Nombre del bucket'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Ejecutar Terraform
      run: |
        aws sts get-caller-identity
        cd modules/bucket/
        terraform init
        terraform apply -auto-approve -var="bucket_name=${{ github.event.inputs.bucket_name }}" -var="environment=${{ github.event.inputs.environment }}"
